LABEL maintainer vsoch

# Testing a github release update
ARG uptodate_github_spack__spack=1.16
ARG uptodate_github_spack__spack=

# Testing a spack version update
ARG uptodate_spack_ace=6.5.6

RUN apt-get update && apt-get install -y vim
